//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

namespace System
{
    public static class DecimalExtensions
    {
        public static decimal Abs(this decimal value)
        {
            return Math.Abs(value);
        }

        public static double Sqrt(this decimal value)
        {
            return Math.Sqrt((double)value);
        }

        public static decimal Pow(this decimal value)
        {
            return value * value;
        }

        public static decimal Pow(this decimal value, int power)
        {
            switch (power)
            {
                case 2: return Pow(value);
                case 3: return Pow(value) * value;
                case 4: return Pow(value) * Pow(value);
                case 6: return Pow(value) * Pow(value) * Pow(value);
                case 8: return Pow(value) * Pow(value) * Pow(value) * Pow(value);
            }

            throw new NotImplementedException();
        }

        public static bool IsBetween(this decimal value, decimal lower, decimal upper)
        {
            return value >= lower && value <= upper;
        }

        public static bool IsBetween(this decimal value, decimal lower, double upper)
        {
            return value >= lower && value <= (decimal)upper;
        }
    }
}
