//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2017. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Data.DbTypes;
using System.Geometries;
using System.IO;

namespace System.Data.Dxf
{
    internal class DxfDataType : DbDataType
    {
        public DxfDataType(string name, Type systemType)
            : base(name, systemType)
        {
        }

        public static DbDataType Int32
        {
            get { return new DxfDataType("Int32", Types.Int32); }
        }

        public static DbDataType Single
        {
            get { return new DxfDataType("Single", Types.Single); }
        }

        public static DbDataType Double
        {
            get { return new DxfDataType("Double", Types.Double); }
        }

        public static DbDataType String
        {
            get { return new DxfDataType("String", Types.String); }
        }

        public static DbDataType DateTime
        {
            get { return new DxfDataType("DateTime", Types.DateTime); }
        }

        public static DbDataType Binary
        {
            get { return new DxfDataType("Binary", Types.Bytes); }
        }

        public static DbDataType Geometry
        {
            get { return new DxfDataType("Geometry", typeof(IGeometry)) { IsShape = true }; }
        }
    }
}
