//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2017. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Collections;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Security.Accounts;
using System.Windows.Forms;

namespace System.Security
{
    [Guid("A4FC4444-2CFE-4F09-97D5-E7FB4F021D31")]
    internal sealed class SubscriptionLicense : SystemLicense
    {
        //private IForm SubscriptionDialog;
        //private static readonly Hashtable SyncRoot = new Hashtable();

        protected override bool OnValidate()
        {
            return true;

            //if (LicenseFile.IsOnline && LicenseFile.IsValid())
            //{
            //    return true;
            //}
            //else
            //{
            //    if (SyncRoot.Count == 0 || DateTime.Now.Subtract((DateTime)SyncRoot["n"]).TotalMinutes > 1.0)
            //    {
            //        try
            //        {
            //            if (NetworkTime.GetNetworkTime(out LicenseFile.NetworkTime))
            //            {
            //                OnValidating(this, default(DoWorkEventArgs));
            //            }
            //        }
            //        catch (Exception e)
            //        {
            //            e.Print();
            //        }
            //    }

            //    SyncRoot["n"] = DateTime.Now;

            //    if (LicenseFile.IsOnline && LicenseFile.IsValid())
            //    {
            //        return true;
            //    }

            //    if (!LicenseFile.IsEmbedded)
            //    {
            //        using (var dialog = Activator.CreateInstance(ApplicationEnvironment.GetType("System.Windows.Forms.ApplicationSubscriptionDialog, System.Windows.Forms.Core")) as Form)
            //        {
            //            if (dialog.HasValue())
            //            {
            //                SubscriptionDialog = dialog as IForm;
            //                SubscriptionDialog.AcceptAction += OnValidating;

            //                Application.Run(dialog);

            //                if (dialog.DialogResult == DialogResult.OK)
            //                {
            //                    return LicenseFile.IsValid();
            //                }

            //                SystemLicense.Kill();
            //            }
            //        }
            //    }
            //}

            //return false;
        }

        //void OnValidating(object sender, DoWorkEventArgs e)
        //{
        //    if (SubscriptionDialog.IsNull())
        //    {
        //        AccountManagerInternal.LicenseFile.Current.SendRequest();
        //    }
        //    else
        //    {
        //        AccountManagerInternal.LicenseFile.Current.SendRequest(SubscriptionDialog.FindValue("UserName") as string, SubscriptionDialog.FindValue("Password") as string);
        //    }
        //}
    }
}
