//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

namespace System.IO.Compression
{
    public enum ZipMethod : short
    {
        /// <summary>
        /// 0 - The file is stored (no compression)
        /// </summary>
        Stored,

        /// <summary>
        /// 1 - The file is Shrunk
        /// </summary>
        Shrunk,

        /// <summary>
        /// 2 - The file is Reduced with compression factor 1
        /// </summary>
        CompressionFactor1,

        /// <summary>
        /// 3 - The file is Reduced with compression factor 2
        /// </summary>
        CompressionFactor2,

        /// <summary>
        /// 4 - The file is Reduced with compression factor 3
        /// </summary>
        CompressionFactor3,

        /// <summary>
        /// 5 - The file is Reduced with compression factor 4
        /// </summary>
        CompressionFactor4,

        /// <summary>
        /// 6 - The file is Imploded
        /// </summary>
        Imploded,

        /// <summary>
        /// 7 - Reserved for Tokenizing compression algorithm
        /// </summary>
        ReservedTokenizing,

        /// <summary>
        /// 8 - The file is Deflated
        /// </summary>
        Deflated,

        /// <summary>
        /// 9 - Enhanced Deflating using Deflate64
        /// </summary>
        Deflate64
    }
}
