//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2017. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

namespace System.Data.Dxf
{
    [Flags]
    internal enum AcDbPolylineFlag : byte
    {
        Default = 0,

        /// <summary>
        /// This is a closed polyline (or a polygon mesh closed in the M direction)
        /// </summary>
        Closed = 1,

        /// <summary>
        /// Curve-fit vertices have been added
        /// </summary>
        CurveFit = 2,

        /// <summary>
        /// Spline-fit vertices have been added
        /// </summary>
        SplineFit = 4,

        /// <summary>
        /// This is a 3D polyline
        /// </summary>
        Polyline3D = 8,

        /// <summary>
        /// This is a 3D polygon mesh
        /// </summary>
        Mesh3D = 16,

        /// <summary>
        /// The polygon mesh is closed in the N direction
        /// </summary>
        MeshClosed = 32,

        /// <summary>
        /// The polyline is a polyface mesh
        /// </summary>
        PolyfaceMesh = 64,

        /// <summary>
        /// The linetype pattern is generated continuously around the vertices of this polyline
        /// </summary>
        LinetypePattern = 128
    }
}
