//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Resources.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALFKI;Alfreds Futterkiste;Maria Anders;Sales Representative;Obere Str. 57;Berlin;;12209;Germany;030-0074321;030-0076545
        ///ANATR;Ana Trujillo Emparedados y helados;Ana Trujillo;Owner;Avda. de la Constitución 2222;México D.F.;;05021;Mexico;(5) 555-4729;(5) 555-3745
        ///ANTON;Antonio Moreno Taquería;Antonio Moreno;Owner;Mataderos  2312;México D.F.;;05023;Mexico;(5) 555-3932;
        ///AROUT;Around the Horn;Thomas Hardy;Sales Representative;120 Hanover Sq.;London;;WA1 1DP;UK;(171) 555-7788;(171) 555-6750
        ///BERGS;Berglunds sn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;Davolio;Nancy;Sales Representative;Ms.;1948-12-08 00:00:00.000;1992-05-01 00:00:00.000;507 - 20th Ave. E. Apt. 2A;Seattle;WA;98122;USA;(206) 555-9857;5467;0x151C2F00020000000D000E0014002100FFFFFFFF4269746D617020496D616765005061696E742E506963747572650001050000020000000700000050427275736800000000000000000020540000424D20540000000000007600000028000000C0000000DF0000000100040000000000A0530000CE0E0000D80E0000000000000000000000000000000080000080000000808000800000008000800080800000C0C0C000808080000000FF0000FF00000 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10248;11;14,00;12;0
        ///10248;42;9,80;10;0
        ///10248;72;34,80;5;0
        ///10249;14;18,60;9;0
        ///10249;51;42,40;40;0
        ///10250;41;7,70;10;0
        ///10250;51;42,40;35;0,15
        ///10250;65;16,80;15;0,15
        ///10251;22;16,80;6;0,05
        ///10251;57;15,60;15;0,05
        ///10251;65;16,80;20;0
        ///10252;20;64,80;40;0,05
        ///10252;33;2,00;25;0,05
        ///10252;60;27,20;40;0
        ///10253;31;10,00;20;0
        ///10253;39;14,40;42;0
        ///10253;49;16,00;40;0
        ///10254;24;3,60;15;0,15
        ///10254;55;19,20;21;0,15
        ///10254;74;8,00;21;0
        ///10255;2;15,20;20;0
        ///10255;16;13,90;35;0
        ///10255;36;15,20;25;0
        ///10255;59;44,00 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10,248.00;VINET;5.00;04.07.1996;01.08.1996;16.07.1996;3.00;32.38;Vins et alcools Chevalier;59 rue de l&apos;Abbaye;Reims;;51100;France
        ///10,249.00;TOMSP;6.00;05.07.1996;16.08.1996;10.07.1996;1.00;11.61;Toms Spezialitäten;Luisenstr. 48;Münster;;44087;Germany
        ///10,250.00;HANAR;4.00;08.07.1996;05.08.1996;12.07.1996;2.00;65.83;Hanari Carnes;Rua do Paço, 67;Rio de Janeiro;RJ;05454-876;Brazil
        ///10,251.00;VICTE;3.00;08.07.1996;05.08.1996;15.07.1996;1.00;41.34;Victuailles en stock;2, rue du Commerce;Lyon;;69004;France
        ///10, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.00;Chai;1.00;1.00;10 boxes x 20 bags;18.00;39.00;0.00;10.00;false
        ///2.00;Chang;1.00;1.00;24 - 12 oz bottles;19.00;17.00;40.00;25.00;false
        ///3.00;Aniseed Syrup;1.00;2.00;12 - 550 ml bottles;10.00;13.00;70.00;25.00;false
        ///4.00;Chef Anton&apos;s Cajun Seasoning;2.00;2.00;48 - 6 oz jars;22.00;53.00;0.00;0.00;false
        ///5.00;Chef Anton&apos;s Gumbo Mix;2.00;2.00;36 boxes;21.35;0.00;0.00;0.00;true
        ///6.00;Grandma&apos;s Boysenberry Spread;3.00;2.00;12 - 8 oz jars;25.00;120.00;0.00;25.00;false
        ///7.00;Uncle Bob&apos;s Organic Dried Pears;3.0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1;Speedy Express;(503) 555-9831
        ///2;United Package;(503) 555-3199
        ///3;Federal Shipping;(503) 555-9931
        ///.
        /// </summary>
        public static string Shippers {
            get {
                return ResourceManager.GetString("Shippers", resourceCulture);
            }
        }
    }
}
