//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Reflection;
using System.Runtime.InteropServices;
using System.Web.UI;

[assembly: AssemblyTitle("Resources Library")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("GISExpress")]
[assembly: AssemblyProduct("GISExpress")]
[assembly: AssemblyCopyright("Copyright © GISExpress 2015-2022. All Rights Reserved.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("0e21a372-619f-45a6-9249-c6be9441c074")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.59")]

[assembly: WebResource("System.Resources.Images16.Wait.gif", "image/gif")]
[assembly: WebResource("System.Resources.Images16.Cancel.png", "image/png")]
[assembly: WebResource("System.Resources.Images16.Category.png", "image/png")]
[assembly: WebResource("System.Resources.Images16.Delete.png", "image/png")]
[assembly: WebResource("System.Resources.Images16.DocumentNew.png", "image/png")]
[assembly: WebResource("System.Resources.Images16.Edit.png", "image/png")]
[assembly: WebResource("System.Resources.Images16.FormClose.png", "image/png")]
[assembly: WebResource("System.Resources.Images16.Okay.png", "image/png")]
[assembly: WebResource("System.Resources.Images16.OpenFolder.png", "image/png")]
[assembly: WebResource("System.Resources.Images16.UploadToCloud.png", "image/png")]

[assembly: WebResource("System.Resources.Images24.Hand.png", "image/png")]
[assembly: WebResource("System.Resources.Images24.Info.png", "image/png")]
[assembly: WebResource("System.Resources.Images24.Search.png", "image/png")]
[assembly: WebResource("System.Resources.Images24.Point.png", "image/png")]
[assembly: WebResource("System.Resources.Images24.Polygon.png", "image/png")]
[assembly: WebResource("System.Resources.Images24.Polyline.png", "image/png")]
[assembly: WebResource("System.Resources.Images24.EditPath.png", "image/png")]
[assembly: WebResource("System.Resources.Images24.ZoomExtents.png", "image/png")]
[assembly: WebResource("System.Resources.Images24.ZoomWindow.png", "image/png")]

[assembly: WebResource("System.Resources.Images32.CursorCross.png", "image/png")]

[assembly: WebResource("System.Resources.Images48.Description.png", "image/png")]