//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.IO;

namespace System.CoordinateSystems
{
    internal class LinearUnitCls : Info, ILinearUnit
    {
        public LinearUnitCls(string name, Authority authority, double metersPerUnit)
            : base(name, authority)
        {
            MetersPerUnit = metersPerUnit;
        }

        public static LinearUnitCls Metre
        {
            get { return new LinearUnitCls("Metre", 9001, 1.0); }
        }

        public double MetersPerUnit
        {
            get;
            set;
        }

        public double ToMeter(double value)
        {
            return value * MetersPerUnit;
        }

        public override bool IsEquivalent(object obj)
        {
            var o = obj as LinearUnitCls;

            if (o == null)
            {
                return false;
            }

            return (MetersPerUnit - o.MetersPerUnit).Abs() < 1e-8;
        }

        public static bool Read(ITokenEnumerator e, out ILinearUnit value)
        {
            if (e.Current.Equals(','))
            {
                e.MoveNext();
            }

            if (e.Current.Equals("UNIT") && e.ReadNext('['))
            {
                if (ReadName(e, out string name) && e.Current.Equals(',') && e.ReadNumber(out NumberToken metersPerUnit))
                {
                    if (e.MoveNext())
                    {
                        ReadAuthority(e, out Authority authority);

                        if (e.Current.Equals(']'))
                        {
                            e.MoveNext();
                            value = new LinearUnitCls(name, authority, Convert.ToDouble(metersPerUnit.Value));
                            return true;
                        }
                    }
                }
            }

            value = null;
            return false;
        }

        public override string ToString()
        {
            var s = string.Concat(@"UNIT[""", Name, @""",", MetersPerUnit.ToText());

            if (!Authority.IsEmpty())
            {
                s = string.Concat(s, ',', Authority);
            }

            return string.Concat(s, "]");
        }
    }
}
