//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Text;

namespace System
{
    public static class Constants
    {
        public const string Trademark = "GISExpress";
        public readonly static HashSet<string> PaletteColors;

        static Constants()
        {
            UTF8 = new UTF8Encoding();
            PaletteColors = new HashSet<string>(StringComparer.InvariantCultureIgnoreCase) { "#BEE8FF", "#D2E5AC", "#FFEABE", "#FFBEBE", "#9ED7C2", "#9EBBD7", "#D7D79E", "#66C2A5", "#E78AC3", "#FFD92F", "#FC8D62", "#E5C494", "#B3B3B3", "#8DA0CB", "#4CB9CC", "#CBD5E8", "#B3E2CD", "#FDCDAC", "#F4CAE4", "#FFF2AE", "#F1E2CC", "#D79E9E", "#CCCCCC" };
        }

        public static readonly UTF8Encoding UTF8;

        public static class Data
        {
            public const string Shp = "Shp";
            public const string Kml = "Kml";

            public const string Id = "Id";
            public const string IdLower = "id";

            public const string FeatureId = "FeatureId";
            public const string FeatureIdLower = "featureid";

            public const string Name = "Name";
            public const string NameLower = "name";

            public const string Shape = "Shape";
            public const string ShapeLower = "shape";

            public const string Geometry = "Geometry";
            public const string GeometryLower = "geometry";

            public const string Provider = "Provider";
            public const string DataSource = "Data Source";
        }

        public static class Xml
        {
            public const string Kml = "kml";
            public const string NamespaceURI = "";
            public const string Document = "Document";
            public const string Folder = "Folder";
            public const string Placemark = "Placemark";
            public const string Style = "Style";
            public const string LineStyle = "LineStyle";
            public const string PolyStyle = "PolyStyle";
            public const string LabelStyle = "LabelStyle";
            public const string IconStyle = "IconStyle";
            public const string Preview = "preview";
            public const string Template = "template";
            public const string Properties = "properties";

            public const string Id = "id";
            public const string Type = "type";
            public const string Name = "name";
            public const string Description = "description";
            public const string Open = "open";
            public const string Visibility = "visibility";
            public const string StyleUrl = "styleUrl";
            public const string ReadOnly = "readOnly";
            public const string Removable = "removable";

            public const string Box = "Box";
            public const string Point = "Point";
            public const string MultiPoint = "MultiPoint";
            public const string LineString = "LineString";
            public const string MultiLineString = "MultiLineString";
            public const string Polygon = "Polygon";
            public const string MultiPolygon = "MultiPolygon";
            public const string GeometryCollection = "GeometryCollection";
            public const string LinearRing = "LinearRing";
            public const string OuterBoundaryIs = "outerBoundaryIs";
            public const string InnerBoundaryIs = "innerBoundaryIs";
            public const string Coordinate = "Coordinate";
            public const string Coordinates = "coordinates";

            public const string Arc = "Arc";
            public const string Circle = "Circle";
            public const string Rectangle = "Rectangle";
            public const string Ellipse = "Ellipse";

            public const string LowerCorner = "lowerCorner";
            public const string UpperCorner = "upperCorner";

            public const string StartAngle = "startAngle";
            public const string SweepAngle = "sweepAngle";

            public static readonly ISet<string> DocumentOrFolder = new HashSet<string> { Document, Folder };
        }

        public static class Sql
        {
            public const char KeywordAsteriskChar = '*';
            public const string KeywordAsteriskString = "*";

            public const string ParameterPrefix = "@";

            public const string KeywordAs = "As";
            public const string KeywordAnd = "And";
            public const string KeywordOr = "Or";
            public const string KeywordIs = "Is";
            public const string KeywordIsNot = "Is Not";
            public const string KeywordDistinct = "Distinct";
            public const string KeywordSelect = "Select";
            public const string KeywordInsert = "Insert";
            public const string KeywordUpdate = "Update";
            public const string KeywordDelete = "Delete";
            public const string KeywordDeclare = "Declare";
            public const string KeywordInto = "Into";
            public const string KeywordSet = "Set";
            public const string KeywordValues = "Values";
            public const string KeywordAdd = "Add";
            public const string KeywordFrom = "From";
            public const string KeywordLeft = "Left";
            public const string KeywordRight = "Right";
            public const string KeywordInner = "Inner";
            public const string KeywordOuter = "Outer";
            public const string KeywordJoin = "Join";
            public const string KeywordWhere = "Where";
            public const string KeywordOrder = "Order";
            public const string KeywordHaving = "Having";
            public const string KeywordGroup = "Group";
            public const string KeywordBy = "By";
            public const string KeywordOrderAsc = "Asc";
            public const string KeywordOrderDesc = "Desc";
            public const string KeywordCreate = "Create";
            public const string KeywordAlter = "Alter";
            public const string KeywordDrop = "Drop";
            public const string KeywordDatabase = "Database";
            public const string KeywordTable = "Table";
            public const string KeywordColumn = "Column";
            public const string KeywordIdentity = "Identity";
            public const string KeywordIndex = "Index";
            public const string KeywordUnique = "Unique";
            public const string KeywordPrimary = "Primary";
            public const string KeywordSpatial = "Spatial";
            public const string KeywordType = "Type";
            public const string KeywordKey = "Key";
            public const string KeywordOn = "On";
            public const string KeywordNot = "Not";
            public const string DbNull = "Null";

            public const string Count = "Count";
            public const string Avg = "Avg";
            public const string Max = "Max";
            public const string Min = "Min";
            public const string Sum = "Sum";
        }
    }
}
