//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

namespace System
{
    public enum WindowsMessage
    {
        Null = 0x0000,
        Create = 0x0001,
        Destroy = 0x0002,
        Move = 0x0003,
        Size = 0x0005,
        Activate = 0x0006,
        SetFocus = 0x0007,
        KillFocus = 0x0008,
        Enable = 0x000A,
        SetRedraw = 0x000B,
        SetText = 0x000C,
        GetText = 0x000D,
        GetTextLength = 0x000E,
        Paint = 0x000F,
        Close = 0x0010,
        QueryEndSession = 0x0011,
        QueryOpen = 0x0013,
        EndSession = 0x0016,
        Quit = 0x0012,
        EraseBackground = 0x0014,
        SystemColorChange = 0x0015,
        ShowWindow = 0x0018,
        WindowsIniChange = 0x001A,
        SettingChange = WindowsIniChange,
        DevModeChange = 0x001B,
        ActivateApp = 0x001C,
        FontChange = 0x001D,
        TimeChange = 0x001E,
        CancelMode = 0x001F,
        SetCursor = 0x0020,
        MouseActivate = 0x0021,
        ChildActivate = 0x0022,
        QueueSync = 0x0023,
        GetMinMaxInfo = 0x0024,
        PaintIcon = 0x0026,
        IconEraseBackground = 0x0027,
        NextDlgCtl = 0x0028,
        SpoolerStatus = 0x002A,
        DrawItem = 0x002B,
        MeasureItem = 0x002C,
        DeleteItem = 0x002D,
        VKeyToItem = 0x002E,
        CharToItem = 0x002F,
        SetFont = 0x0030,
        GetFont = 0x0031,
        SetHotKey = 0x0032,
        GetHotKey = 0x0033,
        QueryDragIcon = 0x0037,
        CompareItem = 0x0039,
        GetObject = 0x003D,
        Compacting = 0x0041,
        Commnotify = 0x0044,
        WindowPosChanging = 0x0046,
        WindowPosChanged = 0x0047,
        Power = 0x0048,
        CopyData = 0x004A,
        CancelJournal = 0x004B,
        Notify = 0x004E,
        InputLangChangeRequest = 0x0050,
        InputLangChange = 0x0051,
        TCard = 0x0052,
        Help = 0x0053,
        UserChanged = 0x0054,
        NotifyFormat = 0x0055,
        ContextMenu = 0x007B,
        StyleChanging = 0x007C,
        StyleChanged = 0x007D,
        DisplayChange = 0x007E,
        GetIcon = 0x007F,
        SetIcon = 0x0080,
        NCCreate = 0x0081,
        NCDestroy = 0x0082,
        NCCalcSize = 0x0083,
        NCHitTest = 0x0084,
        NCPaint = 0x0085,
        NCActivate = 0x0086,
        GetDlgCode = 0x0087,
        SyncPaint = 0x0088,


        NCMouseMove = 0x00A0,
        NCLButtonDown = 0x00A1,
        NCLButtonUp = 0x00A2,
        NCLButtonDblClk = 0x00A3,
        NCRButtonDown = 0x00A4,
        NCRButtonUp = 0x00A5,
        NCRButtonDblClk = 0x00A6,
        NCMButtonDown = 0x00A7,
        NCMButtonUp = 0x00A8,
        NCMButtonDblClk = 0x00A9,
        NCXButtonDown = 0x00AB,
        NCXButtonUp = 0x00AC,
        NCXButtonDblClk = 0x00AD,

        InputDeviceChange = 0x00FE,
        Input = 0x00FF,

        KeyFirst = 0x0100,
        KeyDown = 0x0100,
        KeyUp = 0x0101,
        Char = 0x0102,
        DeadChar = 0x0103,
        SysKeydown = 0x0104,
        SysKeyup = 0x0105,
        SysChar = 0x0106,
        SysDeadChar = 0x0107,
        UniChar = 0x0109,
        KeyLast = 0x0109,

        IMEStartComposition = 0x010D,
        IMEEndcomposition = 0x010E,
        IMEComposition = 0x010F,
        IMEKeyLast = 0x010F,

        InitDialog = 0x0110,
        Command = 0x0111,
        SysCommand = 0x0112,
        Timer = 0x0113,
        HScroll = 0x0114,
        VScroll = 0x0115,
        InitMenu = 0x0116,
        InitMenuPopup = 0x0117,
        MenuSelect = 0x011F,
        MenuChar = 0x0120,
        EnterIdle = 0x0121,
        MenurButtonUp = 0x0122,
        MenuDrag = 0x0123,
        MenuGetObject = 0x0124,
        UnInitMenuPopup = 0x0125,
        Menucommand = 0x0126,

        ChangeUIState = 0x0127,
        UpdateUIState = 0x0128,
        QueryUIState = 0x0129,

        CtlColorMsgbox = 0x0132,
        CtlColorEdit = 0x0133,
        CtlColorListbox = 0x0134,
        CtlColorBtn = 0x0135,
        CtlColorDlg = 0x0136,
        CtlColorScrollbar = 0x0137,
        CtlColorStatic = 0x0138,
        MNGetHMenu = 0x01E1,

        Mousefirst = 0x0200,
        MouseMove = 0x0200,
        LButtonDown = 0x0201,
        LButtonUp = 0x0202,
        LButtonDblClk = 0x0203,
        RButtonDown = 0x0204,
        RButtonUp = 0x0205,
        RButtonDblClk = 0x0206,
        MButtonDown = 0x0207,
        MButtonUp = 0x0208,
        MButtonDblClk = 0x0209,
        MouseWheel = 0x020A,
        XButtonDown = 0x020B,
        XButtonUp = 0x020C,
        XButtonDblClk = 0x020D,
        MousehWheel = 0x020E,

        ParentNotify = 0x0210,
        EnterMenuLoop = 0x0211,
        ExitMenuLoop = 0x0212,

        NextMenu = 0x0213,
        Sizing = 0x0214,
        CaptureChanged = 0x0215,
        Moving = 0x0216,

        PowerBroadcast = 0x0218,

        DeviceChange = 0x0219,

        MdiCreate = 0x0220,
        MdiDestroy = 0x0221,
        MdiActivate = 0x0222,
        MdiRestore = 0x0223,
        MdiNext = 0x0224,
        MdiMaximize = 0x0225,
        MdiTile = 0x0226,
        MdiCascade = 0x0227,
        MdiIconArrange = 0x0228,
        MdiGetActive = 0x0229,


        mdisetmenu = 0x0230,
        entersizemove = 0x0231,
        exitsizemove = 0x0232,
        dropfiles = 0x0233,
        mdirefreshmenu = 0x0234,

        IMESetContext = 0x0281,
        IMENotify = 0x0282,
        IMEControl = 0x0283,
        IMECompositionFull = 0x0284,
        IMESelect = 0x0285,
        IMEChar = 0x0286,
        IMERequest = 0x0288,
        IMEKeyDown = 0x0290,
        IMEKeyUp = 0x0291,

        MouseHover = 0x02A1,
        MouseLeave = 0x02A3,
        NCMouseHover = 0x02A0,
        NCMouseLeave = 0x02A2,

        WTSSessionChange = 0x02B1,

        TabletFirst = 0x02c0,
        TabletLast = 0x02df,

        Cut = 0x0300,
        Copy = 0x0301,
        Paste = 0x0302,
        Clear = 0x0303,
        Undo = 0x0304,
        RenderFormat = 0x0305,
        RenderAllFormats = 0x0306,
        DestroyClipboard = 0x0307,
        DrawClipboard = 0x0308,
        PaintClipboard = 0x0309,
        VScrollClipboard = 0x030A,
        SizeClipboard = 0x030B,
        AskCBFormatName = 0x030C,
        ChangeCBChain = 0x030D,
        HScrollClipboard = 0x030E,
        QueryNewPalette = 0x030F,
        PaletteIsChanging = 0x0310,
        PaletteChanged = 0x0311,
        HotKey = 0x0312,

        Print = 0x0317,
        PrintClient = 0x0318,

        AppCommand = 0x0319,

        ThemeChanged = 0x031A,

        ClipboardUpdate = 0x031D,

        DwmCompositionChanged = 0x031E,
        DwmncRenderingChanged = 0x031F,
        DwmColorizationColorChanged = 0x0320,
        DwmWindowMaximizedChange = 0x0321,

        GetLitleBarInfoex = 0x033F,

        HandHeldFirst = 0x0358,
        HandHeldLast = 0x035F,

        AfxFirst = 0x0360,
        AfxLast = 0x037F,

        PenWinFirst = 0x0380,
        PenWinLast = 0x038F,

        App = 0x8000,

        User = 0x0400,

        Reflect = User + 0x1C00,
    }
}