//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2017. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.IO;
using System.Reflection;

namespace System.Runtime
{
    internal class MathFunction : ExpressionFunction, IExpressionFunctionCollection
    {
        protected readonly static Type DeclaringType = typeof(MathFunctions);

        public MathFunction()
        {
        }

        public MathFunction(string name)
        {
            FunctionName = name;
            Parameters = OperandFactory.Default.CreateOperatorCollection(this);
        }

        protected string FunctionName;

        public override bool IsEmpty()
        {
            return Parameters.Count == 0;
        }

        public override bool HasLeftOperand()
        {
            return false;
        }

        public override string GetFunctionName()
        {
            return FunctionName;
        }

        public IEnumerable<string> GetFunctionNames()
        {
            foreach (MethodInfo method in DeclaringType.GetMethods(BindingFlags.Public | BindingFlags.Static))
            {
                yield return method.Name;
            }
        }

        public IExpressionOperatorCollection Parameters
        {
            get;
            protected set;
        }

        public override bool TryParse(ITokenEnumerator e, IExpressionOperator leftOperand, out IExpressionFunction result)
        {
            var o = new MathFunction(FunctionName);

            if (ReadParameters(e, o.Parameters))
            {
                result = o;
                return true;
            }

            result = default(IExpressionFunction);
            return false;
        }

        protected override Type OnPutInstructions(IInstructionEventArgs e)
        {
            return new ValueOperand(DeclaringType, FunctionName, Parameters).PutInstructions(e);
        }

        protected override string OnLegacyToString(ILegacyToStringVisitor visitor)
        {
            throw new NotImplementedException();
        }

        public override IEnumerator<IExpressionOperator> GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }
}
