//////////////////////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © GISExpress 2015-2022. All Rights Reserved.
//  
//  GISExpress .NET API and Component Library
//  
//  The entire contents of this file is protected by local and International Copyright Laws.
//  Unauthorized reproduction, reverse-engineering, and distribution of all or any portion of
//  the code contained in this file is strictly prohibited and may result in severe civil and 
//  criminal penalties and will be prosecuted to the maximum extent possible under the law.
//  
//  RESTRICTIONS
//  
//  THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES ARE CONFIDENTIAL AND PROPRIETARY TRADE SECRETS OF GISExpress
//  THE REGISTERED DEVELOPER IS LICENSED TO DISTRIBUTE THE PRODUCT AND ALL ACCOMPANYING .NET COMPONENTS AS PART OF AN EXECUTABLE PROGRAM ONLY.
//  
//  THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE
//  COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT
//  AND PERMISSION FROM GISExpress
//  
//  CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON ADDITIONAL RESTRICTIONS.
//  
//  Warning: This content was generated by GISExpress tools.
//  Changes to this content may cause incorrect behavior and will be lost if the content is regenerated.
//
///////////////////////////////////////////////////////////////////////////////////////////////////

using System.Text;

namespace System.IO.Compression
{
    public class GZipNativeStream : Stream
    {
        public GZipNativeStream(Stream stream, CompressionMode mode)
            : this(stream, mode, CompressionLevel.Default, false)
        {
        }

        public GZipNativeStream(Stream stream, CompressionMode mode, CompressionLevel level)
            : this(stream, mode, level, false)
        {
        }

        public GZipNativeStream(Stream stream, CompressionMode mode, bool leaveOpen)
            : this(stream, mode, CompressionLevel.Default, leaveOpen)
        {
        }

        public GZipNativeStream(Stream stream, CompressionMode mode, CompressionLevel level, bool leaveOpen)
        {
            BaseStream = new ZlibBaseStream(stream, mode, level, ZlibStreamFlavor.GZip, leaveOpen);
        }

        internal static readonly Encoding Iso8859 = Encoding.GetEncoding("iso-8859-1");
        internal static readonly DateTime UnixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        internal ZlibBaseStream BaseStream;
        protected int HeaderByteCount;
        protected bool FirstReadDone;
        protected bool Disposed;

        public string Comment
        {
            get;
            set;
        }

        public string FileName
        {
            get;
            set;
        }

        public DateTime? LastModified;

        public int Crc32
        {
            get;
            protected set;
        }

        public virtual FlushType FlushMode
        {
            get { return BaseStream.FlushMode; }
            set
            {
                if (Disposed)
                {
                    throw new ObjectDisposedException(GetType().Name);
                }

                BaseStream.FlushMode = value;
            }
        }

        public int BufferSize
        {
            get
            {
                return BaseStream.BufferSize;
            }
            set
            {
                if (Disposed)
                {
                    throw new ObjectDisposedException(GetType().Name);
                }

                if (BaseStream.WorkingBuffer.HasValue())
                {
                    throw new IOException("The working buffer is already set.");
                }

                BaseStream.BufferSize = Math.Max(value, ZlibConstants.WorkingBufferSizeMin);
            }
        }

        public virtual long TotalIn
        {
            get { return BaseStream.Codec.TotalBytesIn; }
        }

        public virtual long TotalOut
        {
            get { return BaseStream.Codec.TotalBytesOut; }
        }

        public override bool CanRead
        {
            get
            {
                if (Disposed)
                {
                    throw new ObjectDisposedException(GetType().Name);
                }

                return BaseStream.StreamBase.CanRead;
            }
        }

        public override bool CanSeek
        {
            get { return false; }
        }

        public override bool CanWrite
        {
            get
            {
                if (Disposed)
                {
                    throw new ObjectDisposedException(GetType().Name);
                }

                return BaseStream.StreamBase.CanWrite;
            }
        }

        public override void Flush()
        {
            if (Disposed)
            {
                throw new ObjectDisposedException(GetType().Name);
            }

            BaseStream.Flush();
        }

        public override long Length
        {
            get { throw new NotImplementedException(); }
        }

        public override long Position
        {
            get
            {
                if (BaseStream.Mode == ZlibBaseStream.StreamMode.Writer)
                {
                    return BaseStream.Codec.TotalBytesOut + HeaderByteCount;
                }

                if (BaseStream.Mode == ZlibBaseStream.StreamMode.Reader)
                {
                    return BaseStream.Codec.TotalBytesIn + BaseStream.GzipHeaderByteCount;
                }

                return 0;
            }

            set { throw new NotImplementedException(); }
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            if (Disposed)
            {
                throw new ObjectDisposedException(GetType().Name);
            }

            int n = BaseStream.Read(buffer, offset, count);

            if (!FirstReadDone)
            {
                FirstReadDone = true;
                FileName = BaseStream.GzipFileName;
                Comment = BaseStream.GzipComment;
            }

            return n;
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            throw new NotImplementedException();
        }

        public override void SetLength(long value)
        {
            throw new NotImplementedException();
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            if (Disposed)
            {
                throw new ObjectDisposedException(GetType().Name);
            }

            if (BaseStream.Mode == ZlibBaseStream.StreamMode.Undefined)
            {
                if (BaseStream._wantCompress)
                {
                    HeaderByteCount = EmitHeader();
                }
                else
                {
                    throw new InvalidOperationException();
                }
            }

            BaseStream.Write(buffer, offset, count);
        }

        int EmitHeader()
        {
            byte[] commentBytes = (Comment.IsNull()) ? null : Iso8859.GetBytes(Comment);
            byte[] filenameBytes = (FileName.IsNull()) ? null : Iso8859.GetBytes(FileName);

            int cbLength = (Comment.IsNull()) ? 0 : commentBytes.Length + 1;
            int fnLength = (FileName.IsNull()) ? 0 : filenameBytes.Length + 1;

            int bufferLength = 10 + cbLength + fnLength;
            byte[] header = new byte[bufferLength];
            int i = 0;
            // ID
            header[i++] = 0x1F;
            header[i++] = 0x8B;

            // compression method
            header[i++] = 8;
            byte flag = 0;

            if (Comment.HasValue())
            {
                flag ^= 0x10;
            }

            if (FileName.HasValue())
            {
                flag ^= 0x8;
            }

            // flag
            header[i++] = flag;

            // mtime
            if (!LastModified.HasValue) LastModified = DateTime.Now;
            System.TimeSpan delta = LastModified.Value - UnixEpoch;
            Int32 timet = (Int32)delta.TotalSeconds;
            Array.Copy(BitConverter.GetBytes(timet), 0, header, i, 4);
            i += 4;

            // xflg
            header[i++] = 0;    // this field is totally useless
            // OS
            header[i++] = 0xFF; // 0xFF == unspecified

            // extra field length - only if FEXTRA is set, which it is not.
            //header[i++]= 0;
            //header[i++]= 0;

            // filename
            if (fnLength != 0)
            {
                Array.Copy(filenameBytes, 0, header, i, fnLength - 1);
                i += fnLength - 1;
                header[i++] = 0; // terminate
            }

            // comment
            if (cbLength != 0)
            {
                Array.Copy(commentBytes, 0, header, i, cbLength - 1);
                i += cbLength - 1;
                header[i++] = 0; // terminate
            }

            BaseStream.StreamBase.Write(header, 0, header.Length);

            return header.Length; // bytes written
        }

        public static byte[] CompressString(String s)
        {
            using (var ms = new MemoryStream())
            {
                using (Stream compressor = new GZipNativeStream(ms, CompressionMode.Compress, CompressionLevel.BestCompression))
                {
                    ZlibBaseStream.CompressString(s, compressor);
                }

                return ms.ToArray();
            }
        }

        public static byte[] CompressBuffer(byte[] b)
        {
            using (var ms = new MemoryStream())
            {
                using (Stream compressor = new GZipNativeStream(ms, CompressionMode.Compress, CompressionLevel.BestCompression))
                {
                    ZlibBaseStream.CompressBuffer(b, compressor);
                }

                return ms.ToArray();
            }
        }

        public static String UncompressString(byte[] compressed)
        {
            using (var input = new MemoryStream(compressed))
            {
                using (Stream decompressor = new GZipNativeStream(input, CompressionMode.Decompress))
                {
                    return ZlibBaseStream.UncompressString(compressed, decompressor);
                }
            }
        }

        public static byte[] UncompressBuffer(byte[] compressed)
        {
            using (var input = new MemoryStream(compressed))
            {
                using (Stream decompressor = new GZipNativeStream(input, CompressionMode.Decompress))
                {
                    return ZlibBaseStream.UncompressBuffer(compressed, decompressor);
                }
            }
        }

        protected override void Dispose(bool disposing)
        {
            try
            {
                if (!Disposed)
                {
                    if (disposing && (BaseStream.HasValue()))
                    {
                        BaseStream.Close();
                        Crc32 = BaseStream.Crc32;
                    }

                    Disposed = true;
                }
            }
            finally
            {
                base.Dispose(disposing);
            }
        }
    }
}
